# Retry limits
MAX_RETRIES = 3
MAX_PARALLEL_SPLITS = 10
MAX_SPLIT_ROUNDS = 20

# Content validation
MIN_SECTION_SIZE_CHARS = 50
CONTEXT_WINDOW_CHARS = 100
CONTEXT_WORDS_BEFORE = 10
CONTEXT_WORDS_AFTER = 10

# API timeouts (seconds)
INITIAL_API_TIMEOUT_SECONDS = 60
SPLIT_API_TIMEOUT_SECONDS = 30
